#!/usr/bin/env bash
#this script create file and manage some signals
echo $$ > /var/run/myscript.pid
msg1="Y U no love me?!"
msg2="I hate the kill command"
while true; do
  echo "To infinity and beyond"
  trap 'echo $msg1' SIGINT
  trap 'echo $msg2' SIGTERM
  trap "rm /var/run/myscript.pid; exit" SIGQUIT SIGTERM
done
