#!/usr/bin/env bash
#displays To infinity and beyond indefinitely and I am invincible!!!
msg="I am invincible!!!"
while true; do
  echo "To infinity and beyond"
  sleep 2
  trap "echo $msg" SIGTERM
done
