#!/usr/bin/env bash
#this script displays numbers from 1 to 100 in a FizzBuzz format
count=1
while [ $count -lt 101 ]; do
  if [ $((count % 3)) -eq 0 ] && [ $((count % 5)) -ne 0 ]; then
    echo "Fizz"
  elif [ $((count % 5)) -eq 0 ] && [ $((count % 3)) -ne 0 ]; then
    echo "Buzz"
  elif [ $((count % 3)) -eq 0 ] && [ $((count % 5)) -eq 0 ]; then
    echo "FizzBuzz"
  else
    echo $count
  fi
  count=$((count + 1))
done
