#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes
a=0
while [ $a -lt 13 ]; do
  echo "Hour: $a"
  b=1
  while [ $b -lt 60 ]; do
    echo "$b"
    b=$((b + 1))
  done
  a=$((a + 1))
done
